-- 현재 주(2025-08-25) 스케줄 데이터
-- 실행 시간: 2025-08-25T15:46:05.974950

INSERT INTO publishing_schedule (week_start_date, day_of_week, site, topic_category, specific_topic, keywords, target_length, status) VALUES ('2025-08-25', 0, 'unpre', '프로그래밍', 'PyTorch로 컴퓨터 비전 구현', '{}', 'medium', 'planned') ON CONFLICT (week_start_date, day_of_week, site) DO UPDATE SET topic_category = EXCLUDED.topic_category, specific_topic = EXCLUDED.specific_topic;
INSERT INTO publishing_schedule (week_start_date, day_of_week, site, topic_category, specific_topic, keywords, target_length, status) VALUES ('2025-08-25', 0, 'untab', '부동산', '부동산 계약 시 주의사항 완전정리', '{}', 'medium', 'planned') ON CONFLICT (week_start_date, day_of_week, site) DO UPDATE SET topic_category = EXCLUDED.topic_category, specific_topic = EXCLUDED.specific_topic;
INSERT INTO publishing_schedule (week_start_date, day_of_week, site, topic_category, specific_topic, keywords, target_length, status) VALUES ('2025-08-25', 0, 'skewese', '환경', '재활용과 업사이클링의 창조적 실천', '{}', 'medium', 'planned') ON CONFLICT (week_start_date, day_of_week, site) DO UPDATE SET topic_category = EXCLUDED.topic_category, specific_topic = EXCLUDED.specific_topic;
INSERT INTO publishing_schedule (week_start_date, day_of_week, site, topic_category, specific_topic, keywords, target_length, status) VALUES ('2025-08-25', 0, 'tistory', '정치', '북한 핵 위협 지속, 한반도 긴장 고조', '{}', 'medium', 'planned') ON CONFLICT (week_start_date, day_of_week, site) DO UPDATE SET topic_category = EXCLUDED.topic_category, specific_topic = EXCLUDED.specific_topic;
INSERT INTO publishing_schedule (week_start_date, day_of_week, site, topic_category, specific_topic, keywords, target_length, status) VALUES ('2025-08-25', 1, 'unpre', '프로그래밍', 'JWT 토큰 기반 시큐리티 구현', '{}', 'medium', 'planned') ON CONFLICT (week_start_date, day_of_week, site) DO UPDATE SET topic_category = EXCLUDED.topic_category, specific_topic = EXCLUDED.specific_topic;
INSERT INTO publishing_schedule (week_start_date, day_of_week, site, topic_category, specific_topic, keywords, target_length, status) VALUES ('2025-08-25', 1, 'untab', '취미', '친환경 부동산 그린 리모델링 트렌드', '{}', 'medium', 'planned') ON CONFLICT (week_start_date, day_of_week, site) DO UPDATE SET topic_category = EXCLUDED.topic_category, specific_topic = EXCLUDED.specific_topic;
INSERT INTO publishing_schedule (week_start_date, day_of_week, site, topic_category, specific_topic, keywords, target_length, status) VALUES ('2025-08-25', 1, 'skewese', '뷰티/패션', '임진왜란과 이순신의 활약', '{}', 'medium', 'planned') ON CONFLICT (week_start_date, day_of_week, site) DO UPDATE SET topic_category = EXCLUDED.topic_category, specific_topic = EXCLUDED.specific_topic;
INSERT INTO publishing_schedule (week_start_date, day_of_week, site, topic_category, specific_topic, keywords, target_length, status) VALUES ('2025-08-25', 1, 'tistory', '일반', 'MZ세대 투자 패턴 분석, 부작용은?', '{}', 'medium', 'planned') ON CONFLICT (week_start_date, day_of_week, site) DO UPDATE SET topic_category = EXCLUDED.topic_category, specific_topic = EXCLUDED.specific_topic;
INSERT INTO publishing_schedule (week_start_date, day_of_week, site, topic_category, specific_topic, keywords, target_length, status) VALUES ('2025-08-25', 2, 'unpre', '프로그래밍', 'React Hook 고급 활용법', '{}', 'medium', 'planned') ON CONFLICT (week_start_date, day_of_week, site) DO UPDATE SET topic_category = EXCLUDED.topic_category, specific_topic = EXCLUDED.specific_topic;
INSERT INTO publishing_schedule (week_start_date, day_of_week, site, topic_category, specific_topic, keywords, target_length, status) VALUES ('2025-08-25', 2, 'untab', '투자', '고령화 사회와 실버타운 투자', '{}', 'medium', 'planned') ON CONFLICT (week_start_date, day_of_week, site) DO UPDATE SET topic_category = EXCLUDED.topic_category, specific_topic = EXCLUDED.specific_topic;
INSERT INTO publishing_schedule (week_start_date, day_of_week, site, topic_category, specific_topic, keywords, target_length, status) VALUES ('2025-08-25', 2, 'skewese', '역사', '조선시대 과거제도와 교육', '{}', 'medium', 'planned') ON CONFLICT (week_start_date, day_of_week, site) DO UPDATE SET topic_category = EXCLUDED.topic_category, specific_topic = EXCLUDED.specific_topic;
INSERT INTO publishing_schedule (week_start_date, day_of_week, site, topic_category, specific_topic, keywords, target_length, status) VALUES ('2025-08-25', 2, 'tistory', '기술', '전기차 시장 현황과 미래 전망', '{}', 'medium', 'planned') ON CONFLICT (week_start_date, day_of_week, site) DO UPDATE SET topic_category = EXCLUDED.topic_category, specific_topic = EXCLUDED.specific_topic;
INSERT INTO publishing_schedule (week_start_date, day_of_week, site, topic_category, specific_topic, keywords, target_length, status) VALUES ('2025-08-25', 3, 'unpre', '프로그래밍', 'Python 데이터 분석 마스터', '{}', 'medium', 'planned') ON CONFLICT (week_start_date, day_of_week, site) DO UPDATE SET topic_category = EXCLUDED.topic_category, specific_topic = EXCLUDED.specific_topic;
INSERT INTO publishing_schedule (week_start_date, day_of_week, site, topic_category, specific_topic, keywords, target_length, status) VALUES ('2025-08-25', 3, 'untab', '투자', '인플레이션 시대의 투자 가이드', '{}', 'medium', 'planned') ON CONFLICT (week_start_date, day_of_week, site) DO UPDATE SET topic_category = EXCLUDED.topic_category, specific_topic = EXCLUDED.specific_topic;
INSERT INTO publishing_schedule (week_start_date, day_of_week, site, topic_category, specific_topic, keywords, target_length, status) VALUES ('2025-08-25', 3, 'skewese', '역사', '한국 전통 건축의 아름다움과 과학', '{}', 'medium', 'planned') ON CONFLICT (week_start_date, day_of_week, site) DO UPDATE SET topic_category = EXCLUDED.topic_category, specific_topic = EXCLUDED.specific_topic;
INSERT INTO publishing_schedule (week_start_date, day_of_week, site, topic_category, specific_topic, keywords, target_length, status) VALUES ('2025-08-25', 3, 'tistory', '경제', '인플레이션 재부상? 2025년 전망', '{}', 'medium', 'planned') ON CONFLICT (week_start_date, day_of_week, site) DO UPDATE SET topic_category = EXCLUDED.topic_category, specific_topic = EXCLUDED.specific_topic;
INSERT INTO publishing_schedule (week_start_date, day_of_week, site, topic_category, specific_topic, keywords, target_length, status) VALUES ('2025-08-25', 4, 'unpre', '프로그래밍', 'TypeScript 고급 타입 시스템', '{}', 'medium', 'planned') ON CONFLICT (week_start_date, day_of_week, site) DO UPDATE SET topic_category = EXCLUDED.topic_category, specific_topic = EXCLUDED.specific_topic;
INSERT INTO publishing_schedule (week_start_date, day_of_week, site, topic_category, specific_topic, keywords, target_length, status) VALUES ('2025-08-25', 4, 'untab', '투자', '공모주 투자 전략 분석', '{}', 'medium', 'planned') ON CONFLICT (week_start_date, day_of_week, site) DO UPDATE SET topic_category = EXCLUDED.topic_category, specific_topic = EXCLUDED.specific_topic;
INSERT INTO publishing_schedule (week_start_date, day_of_week, site, topic_category, specific_topic, keywords, target_length, status) VALUES ('2025-08-25', 4, 'skewese', '역사', '정조의 개혁 정치와 화성 건설', '{}', 'medium', 'planned') ON CONFLICT (week_start_date, day_of_week, site) DO UPDATE SET topic_category = EXCLUDED.topic_category, specific_topic = EXCLUDED.specific_topic;
INSERT INTO publishing_schedule (week_start_date, day_of_week, site, topic_category, specific_topic, keywords, target_length, status) VALUES ('2025-08-25', 4, 'tistory', '스포츠', '2026 월드컵 공동개최, 한국 축구 재도약', '{}', 'medium', 'planned') ON CONFLICT (week_start_date, day_of_week, site) DO UPDATE SET topic_category = EXCLUDED.topic_category, specific_topic = EXCLUDED.specific_topic;
INSERT INTO publishing_schedule (week_start_date, day_of_week, site, topic_category, specific_topic, keywords, target_length, status) VALUES ('2025-08-25', 5, 'unpre', '프로그래밍', 'GraphQL API 설계와 최적화', '{}', 'medium', 'planned') ON CONFLICT (week_start_date, day_of_week, site) DO UPDATE SET topic_category = EXCLUDED.topic_category, specific_topic = EXCLUDED.specific_topic;
INSERT INTO publishing_schedule (week_start_date, day_of_week, site, topic_category, specific_topic, keywords, target_length, status) VALUES ('2025-08-25', 5, 'untab', '투자', '메타버스 부동산 투자', '{}', 'medium', 'planned') ON CONFLICT (week_start_date, day_of_week, site) DO UPDATE SET topic_category = EXCLUDED.topic_category, specific_topic = EXCLUDED.specific_topic;
INSERT INTO publishing_schedule (week_start_date, day_of_week, site, topic_category, specific_topic, keywords, target_length, status) VALUES ('2025-08-25', 5, 'skewese', '역사', '고구려의 영토 확장과 광개토대왕', '{}', 'medium', 'planned') ON CONFLICT (week_start_date, day_of_week, site) DO UPDATE SET topic_category = EXCLUDED.topic_category, specific_topic = EXCLUDED.specific_topic;
INSERT INTO publishing_schedule (week_start_date, day_of_week, site, topic_category, specific_topic, keywords, target_length, status) VALUES ('2025-08-25', 5, 'tistory', '문화', 'K-문화 글로벌 확산 현황', '{}', 'medium', 'planned') ON CONFLICT (week_start_date, day_of_week, site) DO UPDATE SET topic_category = EXCLUDED.topic_category, specific_topic = EXCLUDED.specific_topic;
INSERT INTO publishing_schedule (week_start_date, day_of_week, site, topic_category, specific_topic, keywords, target_length, status) VALUES ('2025-08-25', 6, 'unpre', '프로그래밍', 'Kubernetes 클러스터 관리', '{}', 'medium', 'planned') ON CONFLICT (week_start_date, day_of_week, site) DO UPDATE SET topic_category = EXCLUDED.topic_category, specific_topic = EXCLUDED.specific_topic;
INSERT INTO publishing_schedule (week_start_date, day_of_week, site, topic_category, specific_topic, keywords, target_length, status) VALUES ('2025-08-25', 6, 'untab', '투자', 'ESG 투자의 미래 전망', '{}', 'medium', 'planned') ON CONFLICT (week_start_date, day_of_week, site) DO UPDATE SET topic_category = EXCLUDED.topic_category, specific_topic = EXCLUDED.specific_topic;
INSERT INTO publishing_schedule (week_start_date, day_of_week, site, topic_category, specific_topic, keywords, target_length, status) VALUES ('2025-08-25', 6, 'skewese', '역사', '조선 후기 실학사상의 발전', '{}', 'medium', 'planned') ON CONFLICT (week_start_date, day_of_week, site) DO UPDATE SET topic_category = EXCLUDED.topic_category, specific_topic = EXCLUDED.specific_topic;
INSERT INTO publishing_schedule (week_start_date, day_of_week, site, topic_category, specific_topic, keywords, target_length, status) VALUES ('2025-08-25', 6, 'tistory', '기술', '전기차 배터리 기술 혁신과 미래', '{}', 'medium', 'planned') ON CONFLICT (week_start_date, day_of_week, site) DO UPDATE SET topic_category = EXCLUDED.topic_category, specific_topic = EXCLUDED.specific_topic;
