name: Scheduled Blog Posts

on:
  schedule:
    # 매일 새벽 3시 (UTC 18시 전날 = KST 3시)
    - cron: '0 18 * * *'
    # 매일 오전 9시 (UTC 0시 = KST 9시)
    - cron: '0 0 * * *'
    # 매일 오후 2시 (UTC 5시 = KST 14시)
    - cron: '0 5 * * *'
    # 매일 저녁 8시 (UTC 11시 = KST 20시)
    - cron: '0 11 * * *'
  workflow_dispatch:
    inputs:
      site:
        description: 'Site to publish (unpre/untab/skewese/all)'
        required: false
        default: 'all'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Trigger Auto Publish via Koyeb API
      run: |
        echo "Triggering auto publish on Koyeb server..."
        
        if [ "${{ github.event.inputs.site }}" == "" ]; then
          echo "Running scheduled posts for all sites..."
          curl -X POST "https://sore-kaile-untab-34c55d0a.koyeb.app/api/quick_publish" \
            -H "Content-Type: application/json" \
            -d '{"sites": ["unpre", "untab", "skewese", "tistory"]}' \
            --max-time 60 || echo "Auto publish failed"
        else
          if [ "${{ github.event.inputs.site }}" == "all" ]; then
            echo "Publishing to all sites..."
            curl -X POST "https://sore-kaile-untab-34c55d0a.koyeb.app/api/quick_publish" \
              -H "Content-Type: application/json" \
              -d '{"sites": ["unpre", "untab", "skewese", "tistory"]}' \
              --max-time 60 || echo "Auto publish failed"
          else
            echo "Publishing to ${{ github.event.inputs.site }}..."
            curl -X POST "https://sore-kaile-untab-34c55d0a.koyeb.app/api/quick_publish" \
              -H "Content-Type: application/json" \
              -d '{"sites": ["${{ github.event.inputs.site }}"]}' \
              --max-time 60 || echo "Auto publish failed"
          fi
        fi
        
        echo "Auto publish request completed"